#!/bin/bash
# $Id: printcontacts,v 1.18 2020/11/10 21:04:16 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/printcontacts,v $
# $Revision: 1.18 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: printcontacts,v 1.18 2020/11/10 21:04:16 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-t | -v] [-l <matrix> i] [ <title> ]"

while [ $# -gt 0 ];do
	case $1 in
		-t) fmt=tif;ext=$fmt;shift ;;
		-j) fmt=jpg;ext=$fmt;shift ;;
		-l) utile=$2;shift 2;;
		-r) fmt=raw;ext=CR2;shift ;;
		*) title="$title $1";shift;;
	esac
done
fmt=${fmt:-jpg}
dir=`basename \`pwd\``
if [ $dir = "jpg" -o $dir = "tif" -o $dir = "raw" ];then 
	cd ../
fi 
dir=`basename \`pwd\``
[ "$title" ] && title=`echo $dir| awk -F- '{print $1,$2}'`
echo "Title: $title"
cd  $fmt 
tot=`ls *.$ext|wc -w`;echo "Frames: $tot"
c=0
m=28

#while [ $tot -gt $m ];do
#	  m=`expr $tot / 2`
#done
while [ $c -lt $tot ]; do
	[ $c -gt 0 ] && { 
		p=`expr $p + 1`
		[ $p -lt 2 ] && p=2
		title="$title ($p)"
	}
	batch=`ls *.$ext |awk 'NR > '$c' && NR <= '$m' {printf "%s ",$1 }'`
	n=`echo $batch|wc -w` 
	c=`expr $c + $n` 
 	[ $n -le 8 ] && tile=4x2
 	[ $n -le 15 -a $n -gt 8 ] && tile=5x3
 	[ $n -gt 15 -a $n -le 24 ] && tile=6x4
 	[ $n -gt 24 -a $n -le 28 ] && tile=7x4
 	#[ $n -gt 28 -a $n -le 32 ] && tile=8x4 
	[ $utile ] && tile=$utile
	 [ "$tile" ] ||{
		echo "$cmd: Don't know layout for $n frames">&2
		exit
	}
        echo "Tile: $tile"	
 	montage -title "$title"  -tile $tile -frame 3  -label %i \
		$batch ../montage$p.jpg
	r=`expr $tot - $m`
	m=`expr $m + $r`
done
