#!/bin/bash
# $Id: printcontacts,v 1.4 2019/06/04 08:29:42 fulford Exp $
# $Source: /src/admin/usr/local/etc/RCS/printcontacts,v $
# $Revision: 1.4 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: printcontacts,v 1.4 2019/06/04 08:29:42 fulford Exp $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-d]  [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-d) set -x;debug=0;shift;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.4 $ $Date: 2019/06/04 08:29:42 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done


while [ $# -gt 0 ];do
	case $1 in
		-t) fmt=tif;shift ;;
		-j) fmt=jpg;shift ;;
		-l) tile=$2;shift 2;;
	esac
done
fmt=${fmt:-jpg}
dir=`basename \`pwd\``
if [ $dir = "jpg" -o $dir = "tif" ];then 
	cd ../
fi 
dir=`basename \`pwd\``
title=`echo $dir| awk -F- '{print $1,$2}'`
echo $title

(cd $fmt
 if [ ! $tile ];then
 	n=`ls|wc -w`
	[ $n -gt 40 ]&&{
		ls |awk 'NR <= 40 {print $1 }'
	}
		
 	case $n in
		24) tile=6x4;;
		25) tile=7x4;;
		30) tile=8x4;;
		36) tile=8x5;;
	 esac
	 [ "$tile" ] ||{
		echo "$cmd: Don't know layout for $n frames">&2
		exit
	 }
 fi
 montage -title "$title"  -tile $tile -frame 5  -label %i  *.$fmt ../montage.jpg
)

